

SCREEN_HEIGHT, SCREEN_WIDTH = 800, 1216
# CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
CENTER = (0.49 * SCREEN_WIDTH, 0.45 * SCREEN_HEIGHT)
ROAD_LINE_MAX_LENGTH = int(SCREEN_HEIGHT * 0.18)
ROAD_LINE_GAP_MAX_LENGTH  = int(SCREEN_HEIGHT * 0.2232)

MEDIAN_LINE_ANGLE = 63.018
HORIZON_HEIGHT = 0.45

OUTPUT_PATH = ".\src\outputs"